config/routes.rb
Ortobom::Application.routes.draw do
  resources :produtos

  resources :vendas

  resources :orcamentos

  resources :usuarios

  resources :clientes

  devise_for :usuarios, :path_prefix => 'devise', :controllers => {:registrations => "registrations"}

  root :to => 'index#index'

end

app/models/orcamento.rb
class Orcamento < ActiveRecord::Base

   has_and_belongs_to_many :produtos
   belongs_to :usuario
   
end

app/controllers/orcamentos_controller.rb
class OrcamentosController < ApplicationController

  before_filter :authenticate_usuario!

  # GET /orcamentos
  # GET /orcamentos.json
  def index
    @orcamentos = Orcamento.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orcamentos }
    end
  end

  # GET /orcamentos/1
  # GET /orcamentos/1.json
  def show
    @orcamento = Orcamento.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @orcamento }
    end
  end

  # GET /orcamentos/new
  # GET /orcamentos/new.json
  def new
    @orcamento = Orcamento.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @orcamento }
    end
  end

  # GET /orcamentos/1/edit
  def edit
    @orcamento = Orcamento.find(params[:id])
  end

  # POST /orcamentos
  # POST /orcamentos.json
  def create
    @orcamento = Orcamento.new(params[:orcamento])
    @orcamento.usuario = current_usuario

    respond_to do |format|
      if @orcamento.save
        format.html { redirect_to @orcamento, notice: 'Orcamento was successfully created.' }
        format.json { render json: @orcamento, status: :created, location: @orcamento }
      else
        format.html { render action: "new" }
        format.json { render json: @orcamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /orcamentos/1
  # PUT /orcamentos/1.json
  def update
    @orcamento = Orcamento.find(params[:id])

    respond_to do |format|
      if @orcamento.update_attributes(params[:orcamento])
        format.html { redirect_to @orcamento, notice: 'Orcamento was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @orcamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orcamentos/1
  # DELETE /orcamentos/1.json
  def destroy
    @orcamento = Orcamento.find(params[:id])
    @orcamento.destroy

    respond_to do |format|
      format.html { redirect_to orcamentos_url }
      format.json { head :ok }
    end
  end
end

app/helpers/orcamentos_helper.rb
module OrcamentosHelper
end

app/views/orcamentos/_form.html.erb
<%= form_for(@orcamento) do |f| %>
  <% if @orcamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@orcamento.errors.count, "error") %> prohibited this orcamento from being saved:</h2>

      <ul>
      <% @orcamento.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br />
    <%= f.text_field :telefone %>
  </div>
  <div class="field">
    <%= f.label :valor_total %><br />
    <%= f.text_field :valor_total %>
  </div>
  <% i = 1; %>
  <% for produto in Produto.find(:all) %>
    <%= check_box_tag "orcamento[produto_ids][]", produto.id, @orcamento.produtos.include?(produto)  %> <%= produto.nome %>
    <% if (i % 5) == 0 %>
      <br /> 
    <% end %>
    <% i = i + 1 %>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orcamentos/edit.html.erb
<h1>Editing orcamento</h1>

<%= render 'form' %>

<%= link_to 'Show', @orcamento %> |
<%= link_to 'Back', orcamentos_path %>

app/views/orcamentos/index.html.erb
<h1>Listing orcamentos</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Email</th>
    <th>Telefone</th>
    <th>Usuario</th>
    <th>Valor total</th>
    <th>Produtos</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @orcamentos.each do |orcamento| %>
  <tr>
    <td><%= orcamento.nome %></td>
    <td><%= orcamento.email %></td>
    <td><%= orcamento.telefone %></td>
    <td><%= orcamento.usuario_id %></td>
    <td><%= orcamento.valor_total %></td>
    <td><%= orcamento.produtos.join(", ") %></td>
    <td><%= link_to 'Show', orcamento %></td>
    <td><%= link_to 'Edit', edit_orcamento_path(orcamento) %></td>
    <td><%= link_to 'Destroy', orcamento, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Orcamento', new_orcamento_path %>

app/views/orcamentos/new.html.erb
<h1>New orcamento</h1>

<%= render 'form' %>

<%= link_to 'Back', orcamentos_path %>

app/views/orcamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @orcamento.nome %>
</p>

<p>
  <b>Email:</b>
  <%= @orcamento.email %>
</p>

<p>
  <b>Telefone:</b>
  <%= @orcamento.telefone %>
</p>

<p>
  <b>Usuario:</b>
  <%= @orcamento.usuario.nome %>
</p>

<p>
  <b>Data:</b>
  <%= @orcamento.created_at.strftime("%d-%m-%Y") %>
</p>

<p>
  <b>Valor total:</b>
  <%= @orcamento.valor_total %>
</p>

<p>
  <b>Produtos:</b>
  <%= @orcamento.produtos.join(", ") %>
</p>

<%= link_to 'Edit', edit_orcamento_path(@orcamento) %> |
<%= link_to 'Back', orcamentos_path %>