config/routes.rb
Ortobom::Application.routes.draw do
  resources :produtos

  resources :vendas

  resources :orcamentos

  resources :usuarios

  resources :clientes

  devise_for :usuarios, :path_prefix => 'devise', :controllers => {:registrations => "registrations"}

  root :to => 'index#index'

end

app/models/produto.rb
class Produto < ActiveRecord::Base
  
  validates_presence_of :cod_produto, :message=>"deve ser preenchido."
  validates_presence_of :nome, :message=>"deve ser preenchido."
  validates_presence_of :preco, :message=>"deve ser preenchido."
  
  has_and_belongs_to_many :vendas
  has_and_belongs_to_many :orcamentos

  def to_s
    nome
  end
  
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController

  before_filter :authenticate_usuario!

  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @produtos }
    end
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
    @produto = Produto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @produto }
    end
  end

  # GET /produtos/new
  # GET /produtos/new.json
  def new
    @produto = Produto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @produto }
    end
  end

  # GET /produtos/1/edit
  def edit
    @produto = Produto.find(params[:id])
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(params[:produto])

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto was successfully created.' }
        format.json { render json: @produto, status: :created, location: @produto }
      else
        format.html { render action: "new" }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /produtos/1
  # PUT /produtos/1.json
  def update
    @produto = Produto.find(params[:id])

    respond_to do |format|
      if @produto.update_attributes(params[:produto])
        format.html { redirect_to @produto, notice: 'Produto was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto = Produto.find(params[:id])
    @produto.destroy

    respond_to do |format|
      format.html { redirect_to produtos_url }
      format.json { head :ok }
    end
  end
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/produtos/_form.html.erb
<%= form_for(@produto) do |f| %>
  <% if @produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
      <% @produto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cod_produto %><br />
    <%= f.text_field :cod_produto %>
  </div>
  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :tamanho %><br />
    <%= f.text_field :tamanho %>
  </div>
  <div class="field">
    <%= f.label :preco %><br />
    <%= f.text_field :preco %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_area :descricao %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/produtos/edit.html.erb
<h1>Editing produto</h1>

<%= render 'form' %>

<%= link_to 'Show', @produto %> |
<%= link_to 'Back', produtos_path %>

app/views/produtos/index.html.erb
<h1>Listing produtos</h1>

<table>
  <tr>
    <th>Cod produto</th>
    <th>Nome</th>
    <th>Tamanho</th>
    <th>Preco</th>
    <th>Descricao</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @produtos.each do |produto| %>
  <tr>
    <td><%= produto.cod_produto %></td>
    <td><%= produto.nome %></td>
    <td><%= produto.tamanho %></td>
    <td><%= produto.preco %></td>
    <td><%= produto.descricao %></td>
    <td><%= link_to 'Show', produto %></td>
    <td><%= link_to 'Edit', edit_produto_path(produto) %></td>
    <td><%= link_to 'Destroy', produto, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Produto', new_produto_path %>

app/views/produtos/new.html.erb
<h1>New produto</h1>

<%= render 'form' %>

<%= link_to 'Back', produtos_path %>

app/views/produtos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cod produto:</b>
  <%= @produto.cod_produto %>
</p>

<p>
  <b>Nome:</b>
  <%= @produto.nome %>
</p>

<p>
  <b>Tamanho:</b>
  <%= @produto.tamanho %>
</p>

<p>
  <b>Preco:</b>
  <%= @produto.preco %>
</p>

<p>
  <b>Descricao:</b>
  <%= @produto.descricao %>
</p>


<%= link_to 'Edit', edit_produto_path(@produto) %> |
<%= link_to 'Back', produtos_path %>