config/routes.rb
Ortobom::Application.routes.draw do
  resources :produtos

  resources :vendas

  resources :orcamentos

  resources :usuarios

  resources :clientes

  devise_for :usuarios, :path_prefix => 'devise', :controllers => {:registrations => "registrations"}

  root :to => 'index#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag :application %>
    <%= javascript_include_tag :application %>
    <%= csrf_meta_tag %>
    <title>Sistema SALC</title>
    <style type="text/css" media="screen">
      body {
        margin: 0;
        margin-bottom: 25px;
        padding: 0;
        background-color: #f0f0f0;
        font-family: "Lucida Grande", "Bitstream Vera Sans", "Verdana";
        font-size: 13px;
        color: #333;
      }

      h1 {
        font-size: 28px;
        color: #000;
      }

      a  {color: #03c}
      a:hover {
        background-color: #03c;
        color: white;
        text-decoration: none;
      }

      #page {
        background-color: #f0f0f0;
        width: 750px;
        margin: 0;
        margin-left: auto;
        margin-right: auto;
      }

      #content {
        float: left;
        background-color: white;
        border: 3px solid #aaa;
        border-top: none;
        padding: 25px;
        width: 500px;
      }

      #sidebar {
        float: right;
        width: 175px;
      }

      #footer {
        clear: both;
      }

      #header, #about, #getting-started {
        padding-left: 75px;
        padding-right: 30px;
      }

      #getting-started {
        border-top: 1px solid #ccc;
        margin-top: 40px;
        padding-top: 15px;
        word-spacing: 40px;
        padding-left: 400px;
      }

      #getting-started h1 {
        margin: 0;
        font-size: 20px;
      }

      #getting-started h2 {
        margin: 0;
        font-size: 14px;
        font-weight: normal;
        color: #333;
        margin-bottom: 25px;
      }

      #getting-started ol {
        margin-left: 0;
        padding-left: 0;
      }

      #getting-started li {
        font-size: 18px;
        color: #888;
        margin-bottom: 25px;
      }

      #getting-started li h2 {
        margin: 0;
        font-weight: normal;
        font-size: 18px;
        color: #333;
      }

      #getting-started li p {
        color: #555;
        font-size: 13px;
      }

      #sidebar ul {
        margin-left: 0;
        padding-left: 0;
      }

      #sidebar ul h3 {
        margin-top: 25px;
        font-size: 16px;
        padding-bottom: 10px;
        border-bottom: 1px solid #ccc;
      }

      #sidebar li {
        list-style-type: none;
      }

      #sidebar ul.links li {
        margin-bottom: 5px;
      }

      .filename {
        font-style: italic;
      }
    </style>

    <%= csrf_meta_tags %>
  </head>
  <body>
    <div>
      <% if usuario_signed_in? %>
        (<%= current_usuario.nome %>)<%= link_to "Logout", destroy_usuario_session_path, :method => :delete %>
	  <% else %>
		<%= link_to "Login", new_usuario_session_path %>
      <% end %>
    </div>
    <h1 align='center'>Sistema SALC</h1>
    <div id="getting-started">
      <a href="/clientes">Clientes</a>
      <a href="/orcamentos">Orcamentos</a>
      <a href="/produtos">Produtos</a>
      <a href="/usuarios">Usuarios</a>
      <a href="/vendas">Venda</a>
    </div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>